
export const url_supabase = "https://htqjcikstmtclneyjjsp.supabase.co"
export const url_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0cWpjaWtzdG10Y2xuZXlqanNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTE1NjkyNTMsImV4cCI6MjAwNzE0NTI1M30.jPDMwuKoybSLcUwiTzKqCQQ19liBfRjC_T_LT5NjGQA"